@startuml

[*] --> WAIT_RISING_EDGE
WAIT_RISING_EDGE -> GENERATE_FILENAME
GENERATE_FILENAME -> OPEN_SOURCE_FILE
OPEN_SOURCE_FILE -> WAIT_OPEN_NOT_BUSY
WAIT_OPEN_NOT_BUSY -> CONVERT_ONE_CSV_RECORD
CONVERT_ONE_CSV_RECORD -> WRITE_RECORD_TO_FILE
WRITE_RECORD_TO_FILE -> WAIT_UNTIL_WRITE_NOT_BUSY
WAIT_UNTIL_WRITE_NOT_BUSY --> CLOSE_SOURCE_FILE
CLOSE_SOURCE_FILE --> WAIT_UNTIL_CLOSE_NOT_BUSY
WAIT_UNTIL_CLOSE_NOT_BUSY --> ERROR_OR_READY_STEP
ERROR_OR_READY_STEP --> [*]

@enduml
